# Generated by Django 3.1.2 on 2020-10-17 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('costo', models.FloatField()),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.area')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_nota', models.IntegerField()),
                ('Descripcion', models.TextField()),
                ('Cantidad', models.FloatField()),
                ('Total', models.FloatField()),
                ('Abono', models.FloatField()),
                ('Cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.cliente')),
                ('Producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.producto')),
            ],
        ),
    ]
